### ISSUE TITLE
#03.01	Interface das Páginas do Cliente

### ISSUE THREAD

**Issue by oo7gabriel** [BarberShop-Manager/BarberShop-Manager#2]
<h1>Desenvolvimento das Interfaces do Cliente</h1>

- [x]  Página de Login Cliente

- [x]  Página de Cadastro

- [x] Página de Cadastro Caso#1: Sucesso

- [x] Página de Cadastro Caso#2: Falha

- [x] Menu Principal

- [x] Perfil

- [x] Alterar dados Perfil

- [x] Tabela de Funcionários do Estabelecimento

- [x] Página de Agendamento

- [x] Página de Agendamento Caso#1: Sucesso

- [x] Pagina de Agendamento Caso#2: Falha
